[package]
name = "nitpick-vulkan"
version = "0.1.0"
description = "Vulkan helper bindings for Nitpick"
authors = ["Randy <randy@example.com>"]

[dependencies]
# None

[build]
shim_libs = ["nitpick_vulkan_shim"]
