[package]
name = "nitpick-tui"
version = "0.1.0"
description = "Text User Interface toolkit"
authors = ["Antigravity"]

[dependencies]
nitpick-display = "path:../nitpick-display"
nitpick-input = "path:../nitpick-input"
nitpick-vec = "path:../nitpick-vec"
nitpick-str = "path:../nitpick-str"
