[package]
name = "nitpick-web-template"
version = "1.0.0"
description = "A production-ready scaffold for building REST APIs with Nitpick"

[dependencies]
nitpick-server = "0.1"
nitpick-router = "0.1"
nitpick-db-pool = "0.1"
nitpick-postgres = "0.1"
nitpick-orm = "0.1"
nitpick-str = "1.0"
