[package]
name = "nitpick-socket"
version = "0.12.0"
description = "TCP and UDP socket abstractions for Nitpick — backed by nitpick-libc_net"
license = "MIT"
categories = ["networking"]

[dependencies]
nitpick-libc = "*"
link_libraries = ["nitpick_libc_net"]
