[package]
name = "nitpick-xml"
version = "0.2.6"
description = "XML parsing and querying for Nitpick"
license = "MIT"
repository = "https://github.com/alternative-intelligence-cp/nitpick-packages"

[dependencies]

[build]
link_libraries = ["nitpick_xml_shim"]
